### ISSUE TITLE
Is it possible to Install on a FAT, then use on Slim?

### ISSUE THREAD

**Issue by oneohthree** [israpps/Funtuna-Fork#20]
If I install Funtuna-Fork manually on a FAT console (to support 190+ consoles), will it work on any Slim console? Does Funtuna-Fork work only on the consoles it was installed on?

**Comment by israpps** [comment]
Everything depends on the hacked icon you installed.

If you picked 190+ it will work on late 50k models and all the slims. Just like the installer clearly says....😐

**Comment by oneohthree** [comment]
Thanks for the quick response. The installer directions are very clear, no doubt about it. My main concern was about installing Funtuna-Fork on a fat to work on a slim. Since Opentuna only works on the console it was installed on, I thought it would be the same behavior for Funtuna-Fork.

**Comment by israpps** [comment]
> Thanks for the quick response. The installer directions are very clear, no doubt about it. My main concern was about installing Funtuna-Fork on a fat to work on a slim. Since Opentuna only works on the console it was installed on, I thought it would be the same behavior for Funtuna-Fork.

Pick the icon for the target console.

And don't open the card on browser from an incompatible console
