### ISSUE TITLE
[bug]: PS1 games launcher

### ISSUE THREAD

**Issue by GKid94** [israpps/Funtuna-Fork#21]
### Issue

Can you add a launcher for PS1 games like OPL in Funtuna menu?

### expected behaviour

I expected...

### Console model

SCPH-90004

### the OpenTuna variant used during install

for Slims and SCPH-5XXXX with 1.90 ROM

### the Installation mode chosen

Installer (auto Install)

**Comment by israpps** [comment]
The public release package includes basic stuff that everyone uses (OPL, wLaunchELF)

PS1 stuff is not.

Add whatever PS1 game launching method you see fit to your own setup

**Comment by GKid94** [comment]
> The public release package includes basic stuff that everyone uses (OPL, wLaunchELF)
> 
> PS1 stuff is not.
> 
> Add whatever PS1 game launching method you see fit to your own setup

I'm not a developer, and I think you will do it better

**Comment by israpps** [comment]
> > The public release package includes basic stuff that everyone uses (OPL, wLaunchELF)
> > PS1 stuff is not.
> > Add whatever PS1 game launching method you see fit to your own setup
> 
> I'm not a developer, and I think you will do it better

you dont need to be a developer to add an application to the menu via the configurator program already bundled

**Comment by GKid94** [comment]
> > > The public release package includes basic stuff that everyone uses (OPL, wLaunchELF)
> > > PS1 stuff is not.
> > > Add whatever PS1 game launching method you see fit to your own setup
> > 
> > 
> > I'm not a developer, and I think you will do it better
> 
> you dont need to be a developer to add an application to the menu via the configurator program already bundled

Yes but it's not tested if it works on this Funtuna
