### ISSUE TITLE
[bug]: uLaunchELF

### ISSUE THREAD

**Issue by nuno6573** [israpps/Funtuna-Fork#23]
### Issue

the problem was
uLE when trying to enter mc0 for the second time it flashes and does not enter mc0

### expected behaviour

I expected...

### Console model

scsph 9xxxx

### the OpenTuna variant used during install

for Slims and SCPH-5XXXX with 1.90 ROM

### the Installation mode chosen

Manual Install

**Comment by israpps** [comment]
duplicate of https://github.com/israpps/wLaunchELF_ISR/issues/13
